In [96]:
import numpy as np
import math
import statistics
import scipy.stats as stats

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


# 1

In [3]:
count = 0
for x in a:
    if x < 0:
        count += 1

count


4

# 2

In [4]:
count = 0
for x in a:
    if x > 0:
        count += 1
count

5

# 3

In [5]:
count = 0
for x in a:
    if (x > 0) and (x % 2 == 0):
        count += 1
count
    

3

# 4

In [6]:
b = a + 3

In [7]:
count = 0
for x in b:
    if x > 0:
        count += 1
count

10

# 5

In [8]:
c = a ** 2

In [19]:
np.mean(c)

74.0

In [18]:
np.std(c)

144.0243035046516

# 6

In [21]:
d = a - np.mean(a)

In [24]:
d

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

# 7

In [35]:
newlist = scipy.stats.zscore(a)
newlist

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# 8

In [36]:

import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
sum_of_a

55

In [38]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = min(a)
min_of_a

1

In [39]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a


10

In [40]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

In [58]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
track = 1
for x in a:
    track = (track * x)
track
product_of_a = track
product_of_a

3628800

In [59]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9,
newlist = []
for x in a:
    newlist.append(x * x)
newlist
squares_of_a = newlist
squares_of_a
    

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [55]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
newlist = [] 
for x in a:
    if x % 2 != 0:
        newlist.append(x)
odds_in_a = newlist
odds_in_a

[1, 3, 5, 7, 9]

In [60]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
newlist = []
for x in a:
    if x % 2 ==0:
        newlist.append(x)
evens_in_a = newlist        
evens_in_a

[2, 4, 6, 8, 10]

In [72]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

sum_of_b

33

In [66]:
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b

3

In [69]:

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])


# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)



In [78]:
# Exercise 9 - print out the shape of the array b.
b.shape

(2, 3)

In [80]:
# Exercise 10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [83]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [84]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [92]:

## Setup 3
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

a = np.min(c)
b = np.max(c)
d = np.sum(c)
e = np.product(c)


362880

In [94]:
# Exercise 2 - Determine the standard deviation of c.
f = np.std(c)


2.581988897471611

In [98]:
# Exercise 3 - Determine the variance of c.
np.var(c)

6.666666666666667

In [99]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [100]:
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [101]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c,c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [103]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
np.sum(c * np.transpose(c))

261

In [104]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
np.product(c * np.transpose(c))

131681894400

In [106]:
## Setup 4
d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

# Exercise 1 - Find the sine of all the numbers in d

In [107]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [108]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [109]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [110]:
# Exercise 4 - Find all the negative numbers in d
newlist = []
for row in d:
    for x in row:
        if x < 0:
            newlist.append(x)
newlist
            
    

[-90, -30, -45, -45]

In [111]:
# Exercise 5 - Find all the positive numbers in d
newlist = []
for row in d:
    for x in row:
        if x > 0:
            newlist.append(x)
newlist

[90, 30, 45, 120, 180, 45, 270, 90, 60, 45, 90, 180]

In [127]:
# Exercise 6 - Return an array of only the unique numbers in d.
newarray = np.array([]) 
for row in d:
    for x in row:
        if x not in newarray:
            newarray = np.append(row,x)
newarray

array([ 60,  45, -45,  90, -45, 180,  60])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.


In [128]:
newlist = []
for row in d:
    for x in row:
        if x not in newlist:
            newlist.append(x)
len(newlist)

11

In [129]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [131]:
# Exercise 9 - Transpose and then print out the shape of d.
d.transpose()

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

In [132]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [ ]:

## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2